# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
    Unity_2022_3_12

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    unityProjectPath: 'C:\Users\apoka\Documents\GitHub\CI-CD_unity_game_01\Ci_cd_unity_game_01'
    versionSelectionMode: 'project'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'Unity_Game_Ci_Android_01'
    



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
